encoder_a_qconfig:
    quantizer: LSQFakeQuantize
    observer: AvgMSEFastObserver
    bit: 4
    symmetric: False
    ch_axis: -1
encoder_w_qconfig:
    quantizer: AdaRoundFakeQuantize
    observer: MSEObserver
    bit: 4
    symmetric: False
    ch_axis: 0
decoder_a_qconfig:
    quantizer: LSQFakeQuantize
    observer: AvgMSEFastObserver
    bit: 4
    symmetric: False
    ch_axis: -1
decoder_w_qconfig:
    quantizer: AdaRoundFakeQuantize
    observer: MSEObserver
    bit: 4
    symmetric: False
    ch_axis: 0
calibrate: 32
recon:
    batch_size: 1
    # scale_lr: 4.0e-5, 5e-3
    scale_lr: 0.002
    weight_lr: 0.001
    warm_up: 0.2
    # weight: 0.01
    weight: 0.02
    iters: 2000
    iters_CAMS: 2000
    b_range: [20, 2]
    keep_gpu: True
    round_mode: learned_hard_sigmoid
    drop_prob: 0.5
ptq4sam:
    BIG: True
    AGQ: True
    global_num: 128
    peak_distance: 32
    peak_height: 0.01
    threshold: 0.5